package entity;
// Generated 09-06-2019 21:57:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="CLIENTE"
    ,schema="CON_FERME"
    , uniqueConstraints = {@UniqueConstraint(columnNames="USER_CLI"), @UniqueConstraint(columnNames="RUT_CLI")} 
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String rutCli;
     private String nomCli;
     private String apellCli;
     private int fonoCli;
     private boolean tipoCli;
     private String razonSocial;
     private String direcCli;
     private String emailCli;
     private String userCli;
     private String passCli;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String rutCli, String nomCli, int fonoCli, boolean tipoCli, String direcCli, String emailCli, String userCli, String passCli) {
        this.idCliente = idCliente;
        this.rutCli = rutCli;
        this.nomCli = nomCli;
        this.fonoCli = fonoCli;
        this.tipoCli = tipoCli;
        this.direcCli = direcCli;
        this.emailCli = emailCli;
        this.userCli = userCli;
        this.passCli = passCli;
    }
    public Cliente(int idCliente, String rutCli, String nomCli, String apellCli, int fonoCli, boolean tipoCli, String razonSocial, String direcCli, String emailCli, String userCli, String passCli, Set<Venta> ventas) {
       this.idCliente = idCliente;
       this.rutCli = rutCli;
       this.nomCli = nomCli;
       this.apellCli = apellCli;
       this.fonoCli = fonoCli;
       this.tipoCli = tipoCli;
       this.razonSocial = razonSocial;
       this.direcCli = direcCli;
       this.emailCli = emailCli;
       this.userCli = userCli;
       this.passCli = passCli;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="ID_CLIENTE", unique=true, nullable=false, precision=8, scale=0)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="RUT_CLI", unique=true, nullable=false, length=10)
    public String getRutCli() {
        return this.rutCli;
    }
    
    public void setRutCli(String rutCli) {
        this.rutCli = rutCli;
    }

    
    @Column(name="NOM_CLI", nullable=false, length=20)
    public String getNomCli() {
        return this.nomCli;
    }
    
    public void setNomCli(String nomCli) {
        this.nomCli = nomCli;
    }

    
    @Column(name="APELL_CLI", length=25)
    public String getApellCli() {
        return this.apellCli;
    }
    
    public void setApellCli(String apellCli) {
        this.apellCli = apellCli;
    }

    
    @Column(name="FONO_CLI", nullable=false, precision=8, scale=0)
    public int getFonoCli() {
        return this.fonoCli;
    }
    
    public void setFonoCli(int fonoCli) {
        this.fonoCli = fonoCli;
    }

    
    @Column(name="TIPO_CLI", nullable=false, precision=1, scale=0)
    public boolean isTipoCli() {
        return this.tipoCli;
    }
    
    public void setTipoCli(boolean tipoCli) {
        this.tipoCli = tipoCli;
    }

    
    @Column(name="RAZON_SOCIAL", length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="DIREC_CLI", nullable=false, length=35)
    public String getDirecCli() {
        return this.direcCli;
    }
    
    public void setDirecCli(String direcCli) {
        this.direcCli = direcCli;
    }

    
    @Column(name="EMAIL_CLI", nullable=false, length=35)
    public String getEmailCli() {
        return this.emailCli;
    }
    
    public void setEmailCli(String emailCli) {
        this.emailCli = emailCli;
    }

    
    @Column(name="USER_CLI", unique=true, nullable=false, length=10)
    public String getUserCli() {
        return this.userCli;
    }
    
    public void setUserCli(String userCli) {
        this.userCli = userCli;
    }

    
    @Column(name="PASS_CLI", nullable=false, length=8)
    public String getPassCli() {
        return this.passCli;
    }
    
    public void setPassCli(String passCli) {
        this.passCli = passCli;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


